config/routes.rb
Rails.application.routes.draw do
  resources :shortners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'shortners#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortner.rb
class Shortner < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shortners_controller.rb
class ShortnersController < ApplicationController
  before_action :set_shortner, only: [:show, :edit, :update, :destroy]

  # GET /shortners
  # GET /shortners.json
  def index
    @shortners = Shortner.all
  end

  # GET /shortners/1
  # GET /shortners/1.json
  def show
    redirect_to @shortner.longurl
  end

  # GET /shortners/new
  def new
    @shortner = Shortner.new
  end

  # GET /shortners/1/edit
  def edit
  end

  # POST /shortners
  # POST /shortners.json
  def create
    @shortner = Shortner.new(shortner_params)

    respond_to do |format|
      if @shortner.save
        format.html { redirect_to root_path, notice: 'Shortner was successfully created.' }
        format.json { render :show, status: :created, location: @shortner }
      else
        format.html { render :new }
        format.json { render json: @shortner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shortners/1
  # PATCH/PUT /shortners/1.json
  def update
    respond_to do |format|
      if @shortner.update(shortner_params)
        format.html { redirect_to root_path, notice: 'Shortner was successfully updated.' }
        format.json { render :show, status: :ok, location: @shortner }
      else
        format.html { render :edit }
        format.json { render json: @shortner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shortners/1
  # DELETE /shortners/1.json
  def destroy
    @shortner.destroy
    respond_to do |format|
      format.html { redirect_to shortners_url, notice: 'Shortner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortner
      @shortner = Shortner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shortner_params
      params.require(:shortner).permit(:longurl, :shorturl, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortners_helper.rb
module ShortnersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Urlshortnr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shortners/_form.html.erb
<div class="form-page">
  <%= form_with(model: shortner, local: true) do |form| %>
    <% if shortner.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(shortner.errors.count, "error") %> prohibited this shortner from being saved:</h2>

        <ul>
        <% shortner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :longurl %>
      <%= form.text_field :longurl, id: :shortner_longurl, class: 'text-field' %>
    </div>

    <div class="field">
      <%= form.label :shorturl %>
      <%= form.text_field :shorturl, id: :shortner_shorturl, class: 'text-field' %>
    </div>

    <div class="field">
      <%= form.label :active %>
      <%= form.check_box :active %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/shortners/edit.html.erb
<div class="edit-page">

  <h1>Editing Shortner</h1>

  <%= render 'form', shortner: @shortner %>

  <%= link_to 'Show', @shortner, class: 'show-button' %> |
  <%= link_to 'Back', shortners_path, class: 'back-button' %>

</div>

app/views/shortners/index.html.erb
<div class="index-page">

  <p id="notice"><%= notice %></p>

  <h1>URL Shortnr</h1>

    <div class="table-div">
      <table>
        <thead>
          <tr>
            <th class="longurl">Longurl</th>
            <th class="shorturl">Shorturl</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>


        <div class="table-content">
          <tbody>
            <% @shortners.each do |shortner| %>
              <tr>
                <td class="longurl-link"><%= shortner.longurl %></td>
                <td class="shorturl-link"><%= link_to shortner.shorturl, shortner.longurl %></td>
                <td><%= link_to 'Show', shortner, class: 'show-button' %></td>
                <td><%= link_to 'Edit', edit_shortner_path(shortner), class: 'edit-button' %></td>
                <td><%= link_to 'Delete', shortner, method: :delete, data: { confirm: 'Are you sure you want to delete this url?' }, class: 'delete-button' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <br>
      <div class="new-button-index-page clearfix">
        <%= link_to 'New Shortner', new_shortner_path, class: 'new-button' %>
      </div>

</div>

app/views/shortners/new.html.erb
<div class="new-page">

  <h1>New Shortner</h1>

  <%= render 'form', shortner: @shortner %>

  <%= link_to 'Back', shortners_path, class: 'back-button' %>

</div>

app/views/shortners/show.html.erb
<div class="show-page">

  <h1>Additional Information</h1>

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Longurl:</strong>
    <%= @shortner.longurl %>
  </p>

  <p>
    <strong>Shorturl:</strong>
    <%= link_to @shortner.shorturl, @shortner.longurl %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= @shortner.active %>
  </p>


  <%= link_to 'Edit', edit_shortner_path(@shortner), class: 'edit-button' %> |
  <%= link_to 'Back', shortners_path, class: 'back-button' %>

</div>